apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: es
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: es
    server: https://kubernetes.default.svc
  source:
    path: argocd
    repoURL: https://github.com/olivierbegon/es.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
